// automatically generated by the FlatBuffers compiler, do not modify

package moe;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class Categories extends Table {
  public static Categories getRootAsCategories(ByteBuffer _bb) { return getRootAsCategories(_bb, new Categories()); }
  public static Categories getRootAsCategories(ByteBuffer _bb, Categories obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public Categories __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public Category categories(int j) { return categories(new Category(), j); }
  public Category categories(Category obj, int j) { int o = __offset(4); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int categoriesLength() { int o = __offset(4); return o != 0 ? __vector_len(o) : 0; }
  public Category categoriesByKey(String key) { int o = __offset(4); return o != 0 ? Category.__lookup_by_key(__vector(o), key, bb) : null; }

  public static int createCategories(FlatBufferBuilder builder,
      int categoriesOffset) {
    builder.startObject(1);
    Categories.addCategories(builder, categoriesOffset);
    return Categories.endCategories(builder);
  }

  public static void startCategories(FlatBufferBuilder builder) { builder.startObject(1); }
  public static void addCategories(FlatBufferBuilder builder, int categoriesOffset) { builder.addOffset(0, categoriesOffset, 0); }
  public static int createCategoriesVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startCategoriesVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static int endCategories(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
  public static void finishCategoriesBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset); }
}

