// automatically generated by the FlatBuffers compiler, do not modify

package moe;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class RadicalTable extends Table {
  public static RadicalTable getRootAsRadicalTable(ByteBuffer _bb) { return getRootAsRadicalTable(_bb, new RadicalTable()); }
  public static RadicalTable getRootAsRadicalTable(ByteBuffer _bb, RadicalTable obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public RadicalTable __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public Radical radicals(int j) { return radicals(new Radical(), j); }
  public Radical radicals(Radical obj, int j) { int o = __offset(4); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int radicalsLength() { int o = __offset(4); return o != 0 ? __vector_len(o) : 0; }
  public Radical radicalsByKey(String key) { int o = __offset(4); return o != 0 ? Radical.__lookup_by_key(__vector(o), key, bb) : null; }

  public static int createRadicalTable(FlatBufferBuilder builder,
      int radicalsOffset) {
    builder.startObject(1);
    RadicalTable.addRadicals(builder, radicalsOffset);
    return RadicalTable.endRadicalTable(builder);
  }

  public static void startRadicalTable(FlatBufferBuilder builder) { builder.startObject(1); }
  public static void addRadicals(FlatBufferBuilder builder, int radicalsOffset) { builder.addOffset(0, radicalsOffset, 0); }
  public static int createRadicalsVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startRadicalsVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static int endRadicalTable(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
  public static void finishRadicalTableBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset); }
}

