// automatically generated by the FlatBuffers compiler, do not modify

package moe;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class UTF16String extends Table {
  public static UTF16String getRootAsUTF16String(ByteBuffer _bb) { return getRootAsUTF16String(_bb, new UTF16String()); }
  public static UTF16String getRootAsUTF16String(ByteBuffer _bb, UTF16String obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public UTF16String __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int u16str(int j) { int o = __offset(4); return o != 0 ? bb.getShort(__vector(o) + j * 2) & 0xFFFF : 0; }
  public int u16strLength() { int o = __offset(4); return o != 0 ? __vector_len(o) : 0; }
  public ByteBuffer u16strAsByteBuffer() { return __vector_as_bytebuffer(4, 2); }

  public static int createUTF16String(FlatBufferBuilder builder,
      int u16strOffset) {
    builder.startObject(1);
    UTF16String.addU16str(builder, u16strOffset);
    return UTF16String.endUTF16String(builder);
  }

  public static void startUTF16String(FlatBufferBuilder builder) { builder.startObject(1); }
  public static void addU16str(FlatBufferBuilder builder, int u16strOffset) { builder.addOffset(0, u16strOffset, 0); }
  public static int createU16strVector(FlatBufferBuilder builder, short[] data) { builder.startVector(2, data.length, 2); for (int i = data.length - 1; i >= 0; i--) builder.addShort(data[i]); return builder.endVector(); }
  public static void startU16strVector(FlatBufferBuilder builder, int numElems) { builder.startVector(2, numElems, 2); }
  public static int endUTF16String(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

